export { default as Signup } from './Signup'
export { default as Login } from './Login'
export { default as Videos } from './Videos'
export { default as History } from './History'
export { default as Home } from './Home'
